db:
  url: jdbc:oracle:thin:@114.242.246.230:1521:orcl
  username: drg_gms
  password: ENC(ABmG91HUH0+AhxAvnB4YBA==)
  driverClassName: oracle.jdbc.OracleDriver

# 数据库访问配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: ${db.driverClassName}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: SELECT 1 FROM DUAL
  # Redis 配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ENC(WOloK72WqIXrQ/xmZ2BgvX8O4ch4/qCf)
    jedis:
      # 链接池
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    timeout: 10000